### ISSUE TITLE
Custom Currency Name

### ISSUE THREAD

**Issue by worldwidee** [nerdy-pro/flutter_number_editing_controller#3]
Hi, thanks for the package. 

It says "TL" even though the symbol for the Turkish lira is "₺". Can you add customCurrencyName to solve such problems. If you are not available, I can also contribute. 

```dart
controller =
      NumberEditingTextController.currency(currencyName: "TRY", value: 0)
```

**Comment by thenixan** [comment]
The question is a bit more complicated :)
For instance if you're on a `en_US` locale, then the currency symbol for the `USD` would be `$` and for `CAD` would be `CA$`, but if you will switch to the `en_CA`, then `USD` would be `US$` and `CAD` – `$`.
On one hand that's a really big change, but still it can be backported from the `java`'s implementation of locales.
But to gain some flexibility I'd say go ahead and make a change proposition

**Comment by thenixan** [comment]
@worldwidee or wait a bit, I will implement it on my own :D

**Comment by worldwidee** [comment]
okay, thank you very much <3. This package is the best one in this field, solved my problem quickly.
Suggestion:
The package name could be better. I think because of the name, people can't find it. Except for that very simple and nice to use

**Comment by thenixan** [comment]
https://github.com/nerdy-pro/flutter_number_editing_controller/blob/a3261f82e2a5822c4390f35785ed8a5860b7fcf7/lib/number_editing_controller.dart#L21 – check it out

Thanks for your feedback

**Comment by thenixan** [comment]
Fixed in version `1.2.1`: https://pub.dev/packages/number_editing_controller/versions/1.2.1

**Comment by worldwidee** [comment]
![Capture](https://github.com/nerdy-pro/flutter_number_editing_controller/assets/49057380/5b8b16ba-b7cc-45a0-93c2-e8866f8831d6)
You can also take a parameter like paddingLetterCount to put a space between currency and text. For example, if 3 is entered for this parameter, 3 " " can be set to the TextEditingController.

**Comment by worldwidee** [comment]
Thank you very much, i will try it soon. Much appreciated

**Comment by thenixan** [comment]
The package internally depends on the `flutter`'s `symbols` implementation from `intl` package, and default formatting is built on top of this `symbols` definition. Some locales have currency symbol in the end of the number and some do not have the separation between digits and symbol at all.

**Comment by thenixan** [comment]
Rica ederim 😌

**Comment by worldwidee** [comment]
hahah :D
